### ISSUE TITLE
Not found on npm

### ISSUE THREAD

**Issue by nie-xin** [Leeds-eBooks/roots-i18n#1]
The plugin could not be found on npm, could you please check module is ready upload to npm?

Anyway, great plugin for roots!

![npm](https://cloud.githubusercontent.com/assets/3535692/11528510/82096bc4-98e7-11e5-8cde-bab98c39cf81.png)

**Comment by benadamstyles** [comment]
Hey, thanks for getting in touch. I am actually waiting for Jeff, the guy behind Roots, to approve my use of the `roots-i18n` package name, in this issue: https://github.com/jenius/roots/issues/189

I will ask again and if he doesn't reply within a week I will go ahead. In the meantime you can still use `npm` with this package:

``` sh
npm i --save https://github.com/Leeds-eBooks/roots-i18n.git
```

When I get this up on `npm` I'll mention it here and close this issue.

**Comment by benadamstyles** [comment]
Ok this is published on npm now. I'll be adding tests and improving it over the coming weeks. If you have any problems, questions or suggestions, please don't hesitate to raise an issue in this repo.

**Comment by nie-xin** [comment]
Cool! I will try to integrate to my small project and give you feedback as soon as possible. Thx :)
